// <auto-generated />
namespace jwt.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateAccountInfoTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateAccountInfoTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202006041121035_updateAccountInfoTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
